### ISSUE TITLE
[OLS-9 Cohort Organisation Checklist]

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/ols-9#1]
# _This is a cohort checklist that covers tasks before, during and after the cohorts_.

Note: each cohort week (the entire cohort has a total of 16 weeks) has several related tasks. Each week has a GitHub-related issue: 
- Week 1: #2
- Week 2: #3
- Week 3: #4
- Week 4: #5
- Week 5: #6
- Week 6: #7
- Week 7: #8
- Week 8: #9
- Week 9: #10
- Week 10: #11
- Week 11: #12
- Week 12: #13
- Week 13: #14
- Week 14: #15
- Week 15: #16
- Week 16: #17 

# On-boarding and training sessions for cohort participants (mentors, facilitators)
- Mentors on-boarding (done by OLS team members) - see [calendar/schedule](https://openlifesci.org/ols-9/schedule/)
- Mentors training (done by 360) - see [calendar/schedule](https://openlifesci.org/ols-9/schedule/)
- Facilitators onboarding + training (done by OLS team members) - see [calendar/schedule](https://openlifesci.org/ols-9/schedule/)

# Check OLS-team if you are unsure of using specific platforms listed below:
- CiviCRM for creating cohort-specific email groups (Learn how to create smart groups)
- OpenReview for applications (Learn how to recruit reviewers in open review (video)
- Share written tutorial for cohort call facilitators (in-call facilitators and transcription checkers)
- Use Restream for graduations (to stream both to otter.ai and to YouTube from Zoom). 
- Create Bitly links for each cohort call (linked to the planning sheet)
- How to create the certificates of completion using Inkscape (at the end of the cohort)

# Set Up Relevant documents/forms
- Key email templates (application acceptance/rejection; 
- CiviCRM weekly cohort email templates (taken from OLS-8)
- Cohort planning sheet
- Cohort GitHub repo (this) with updated issue templates
- Cohort mentor, facilitator and speaker recruitment forms (three could be linked)
- Cohort facilitators sign-up sheet, [example](https://docs.google.com/spreadsheets/d/1MFtAVvkqTejluTWsVMEv_BUQ2M3B3PJmlrknDyHvj6U/edit#gid=522767112) 
- Cohort honoraria form (used by facilitators, mentors, and speakers)
- Cohort CiviCRM sign-up form (all cohort participants must sign up to fully register in the cohort)
- Create issues 1 to 16 linking to each week of the cohort

# Pre-cohort tasks 

1. ## Designate Cohort Call Leads among OLS team members

- [ ] Call leads ask the team to add their names to the cohort’s OLS-9 planning sheet if they plan to attend any of the cohort calls
- [ ] Call leads invite suggestions for speakers for all cohort calls.
- [ ] Call leads must check the Cohort Call Facilitators sign-up sheet and coordinate with their facilitators everything regarding the facilitators’ roles. 
- [ ] Coordinator/Assistant: Add the cohort call leads as “assignees” in the [OLS-8 management board](https://github.com/orgs/open-life-science/projects/7), linking each task to the corresponding cohort week GH issue https://github.com/orgs/open-life-science/projects/4/views/1 
- [ ] Assistant: set up calendar reminders for the key tasks indicated in this cohort checklist 
- [ ] Assistant: create cohort email address, like 8-cohort-management@we-are-ols.org

2. ## Recruit reviewers 
Reviewers are those who read the upcoming project applications. Those who sign up as mentors are expected to act as reviewers, but not all reviewers will be mentors. Some people just volunteer to be reviewers. 
- [ ] Post on Slack to see who wants to be a reviewer (explaining that even if you do not want to be a mentor, you can be a reviewer). Add a link to the CiviCRM form so they register their interest there. 
- [ ] Check Civi to see who signed up as reviewers only, and invite them to review via Open Review. 
- [ ] Check Civi to see who signed up as mentors, and invite them to review via Open Review. 
- [ ] Invite people to accept the reviewer's invitation via an Open Review email (see a tutorial about how to do that in XX).
- [ ] Create a Slack channel for the cohort reviewers, to use to communicate updates and if needed, to ask for extra reviewers (for tricky applications). 

3. ## Recruit mentors (well ahead of the start of the cohort)

- [ ] Coordinator: Post on slack channels reminding people to sign up as mentors, using the CiviCRM form https://openlifescience.civicrm.org/civicrm/event/info?id=4&reset=1 
- [ ] Reviewers are often those who become mentors, so stay communicated with them and ask them one by one if they want to be mentors. 
- [ ] Gather names of people who want to be mentors from the post-cohort survey forms (from both the survey for mentors and the survey for mentees). Ideally email them, one by one, the CiviCRM form so they can register their interest: https://openlifescience.civicrm.org/civicrm/event/info?id=4&reset=1 
- [ ] Go to CiviCRM, get a list of mentors from previous cohorts (who might not be active on Slack), and email them one by one asking if they want to be mentors again in OLS8. 
- [ ] Create a document listing Mentors' responsibilities and rights, also including where registered reviewers/mentors should look for info (are they going to receive emails or should they check Slack?) - maybe when they register they should receive this "READ-ME please" email containing this info.

4. ## Recruit facilitators 
There are 2 types of facilitators: one joins the cohort call and the other does the post-call otter.ai, video editing and uploading to YouTube. The one that helps run the cohort call must also make sure the call’s etherpad is in order before the call starts, and after the call ends must make sure the etherpad is completed and uploaded into Github. A detailed description of what this role entails can be found here. 

- [ ] Post on Slack asking who wants to be a facilitator. Add a link to the role description and the role tutorial. Include the link to the CiviCRM form and ask them to register their interest there. Explain that the idea is to distribute facilitation opportunities among people who do not have other roles in OLS. For example, if someone signed up as a mentor, and has already been assigned a mentee(s), then ideally that person should not sign up as facilitator as well. 
- [ ] Check who signed up as a facilitator in Civi and tag them in a Slack post inviting them to fill out the sign-up sheet

5. ## Manage facilitators
- [ ] 2 weeks before the cohort starts, ask those who registered on Civi to add their names in one or two (not more than 2) cohort calls, in the Call facilitator sign-up sheet. Two facilitators are needed for each cohort call, one that joins the call, and one that does the transcript check and uploading. Remember some calls don’t use facilitation. 

6. ## Organise onboarding for facilitators 
- [ ] Organise one or two onboarding sessions for all the registered facilitators, before the cohort starts, to go through each step of the processes (training materials in the planning folder)

7. ## Organise mentor training & onboarding 
Onboarding calls for mentors are aimed at solving any doubts mentors might have and letting them know what they could do in certain cases (for example:  mentees not responding, mentees being rude). Mentor training is a 3-hour session in which a lot more details are covered. Those who have already attended the training in previous cohorts, don’t need to re-attend (but they can, if they want and there is space). 
- [ ] Find potential dates (2 or 3) for the mentor training sessions (3 hours long). 
- [ ] Find dates for two or three onboarding sessions (1 hour long). These onboarding sessions are hosted by OLS staff. 
- [ ] Invite all mentors to these onboarding sessions, whether they are new mentors or experienced mentors. 
- [ ] Identify who will deliver the training (360 or internal member). Propose to them the selected dates. 
- [ ] Invite all new mentors to all the mentor training sessions (same training, repeated on different days/times), via a calendar invite. Tell them via email and Slack to accept the training session that suits them better. Remind them these sessions aren’t recorded. 
- [ ] Check the onboarding materials are up to date, engaging, clear and concise, for example, the mentors-mentee meetings templates and assignments doc: https://docs.google.com/document/d/1MHwqBOWQfobdM2x3ywB1iHzN5L1by4NFWWMwS8ZjB70/edit 

8. ## Inform successful applicants they have been selected - add them on Slack
- [ ] Send confirmation messages 
- [ ] Send acceptance emails to successful applicants and ask them to confirm they will participate in the program before matching them to mentors and informing them who their mentors are. Tell them to register on Civi and do so as "project leads". Explain we ask them to do this in part so they can start receiving the cohort mailings (which are sent weekly). 
- [ ] After they register on CiviCRM send them an email informing them who their mentors are (copying the mentor). Do not match them unless they reply to the email and confirm their participation. 
- [ ] Add all the confirmed people to Slack - add them to the "old-9-cohort" and the general channel, and send them a tutorial about Slack for those who haven't used it/don't know Slack. 
- [ ] Email all registered mentees asking them if they signed up on Slack and reminding them a lot of the communications happen there

9. ## Match projects + mentors
This project-mentor matching occurs after the reviewing process has been completed. 
- [ ] Create an Excel spreadsheet with all confirmed cohort projects and use it to do the mentor matching. (This Excel spreadsheet can later be used to upload this information -project-mentor matches- onto the website).  
- [ ] Inform projects and mentors whom they’ve been paired with via email. In that email include key information: what to expect and what not to expect from mentors, that they should be the first to contact their mentors directly, calendar link, assignments link, how to join the cohort calls (link on the etherpad which is found in the calendar invite in OLS public calendar), where to look for information, who to contact in case of questions (office hours of cohort organisers).

10. ## Set up CiviCRM mailing for the cohort - and create a management email address
- [ ] Coordinator: Post on Slack and send an email to all participants warning them they should start receiving CiviCRM mailings, and that if they don’t, they should check their spam folder. 
- [ ] Coordinator: Set up smart groups on CiviCRM (using SearchKit) https://docs.civicrm.org/user/en/latest/organising-your-data/smart-groups/ 
- [ ] Coordinator: Check if all mentees and mentors are getting the Civi mailings - check individually with each person via email or Slack.
- [ ] Create an email address equivalent to this one [7-cohort-management@openlifesci.org](mailto:7-cohort-management@openlifesci.org) 

11. ## Add mentors and mentees on Slack
- [ ] Add new mentors to Slack (#general #ols-9-cohort)
- [ ] Add new mentees to Slack
- [ ] Coordinator: Message each mentee individually on Slack - remind them there about your timezone and working hours 
- [ ] Post on Slack the OLS team working days/hours/office hours. 

# At the start of the cohort

12. ## Getting ready for the cohort calls
- [ ]  Assistant or Coordinator: Check if the cohort's weekly GH issues are set up and correct 
- [ ]  Assistant or Coordinator: Check with the call lead of week 1 if the etherpad is ready and the facilitators are confirmed.  
- [ ]  Call leads/hosts should check the Call Facilitator sign-up sheet and make sure their assigned call has the required facilitators. Some calls do not require facilitators (like week 13 on self-help) so if that is the case, it should be clearly shown in the signup sheet to avoid facilitators signing up and then not being able to participate. 

13. ## Getting the cohort communication channels ready 
- [ ] The coordinator should schedule at least the first 2 weekly CiviCRM mailings. Weekly mailings are sent during the cohort to alert participants of all things happening each week. These mailings are sent via CiviCRM. It is advisable to schedule mailings so they are sent early on Mondays. On Civi, we can check previously sent mailings, including those from previous cohorts, and we can use them as templates if needed. Here is a compendium of all the mailings from a previous cohort: https://docs.google.com/document/d/1wGNSXGux_Ziws_VlPRoeaWQtorpRFKjiYXBy9iKl3DE/edit# 
- [ ] Create or update [Q&A document] (https://docs.google.com/document/d/1x-_Ai0vTPP18Dql9fsunPJg-fkmr9sEh1QOSmrmG76E/edit)

# Three weeks before each cohort call

14. ## Checking if the communication channels are reaching people 
- [ ]  After sending the first week’s mailing, ask mentees and mentors one by one if they received the mailing. Doing this is time-consuming, but will save your problems and a lot of your time later on in the cohort.

15. ## Double check cohort call roles are being fulfilled & documentation is ready 
- [ ]  Executive assistant: Find who is the call leads in the OLS-9 Planning Spreadsheet (the person from the team that leads each cohort call) 
- [ ]  Executive assistant: Confirm the call lead/host can be there at the call. If yes, send the calendar invite and expect a quick calendar confirmation. If the call lead cannot attend, ask the Coordinator to find another call lead.
- [ ] Call lead/host: Nominate speakers. *Note*: please double-check if the nominated speakers did not do the same call in previous cohorts. The idea is not to repeat speakers from previous cohorts. Check this info in the OLS8 Planning Spreadsheet.
- [ ] Executive assistant: Invite speakers by email using [email templates](https://docs.google.com/document/d/1Go_na0zqY6_17FBNlX8xCD5hUd5FaaByth1EHoRH0T4/edit) (cc Call lead/host)
- [ ] Executive assistant: Confirm speaker/send information w [email templates](https://docs.google.com/document/d/1Go_na0zqY6_17FBNlX8xCD5hUd5FaaByth1EHoRH0T4/edit) (cc Call lead/host)
- [ ] Executive assistant: Invite speakers with calendar event (cc Call lead/host)
- [ ] Executive assistant: Confirm facilitator link to facilitator sign up
- [ ]  Executive assistant: Add facilitators to calendar invite ([OLS Public calenda](https://calendar.google.com/calendar/u/0?cid=b3BlbmxpZmVzY2lAZ21haWwuY29t)r)
- [ ] Call lead/host: Add the names of the confirmed speakers to the OLS8 Planning Spreadsheet (columns T to Y).
- [ ] Call lead/host: Prepare Etherpad. This includes creating the etherpad link by entering here: https://pad.sfconservancy.org/ (add/use this format: ols-8-week-01) and adding this pad link to the OLS8 Planning Spreadsheet. (Check tutorial on how to create the bit.ly link in the policies and procedures repo.)
- [ ] Call lead/host + Executive assistant: Double check Etherpad is ok. Make sure to add the Host, Facilitator, Speakers and links to the PowerPoint presentations if speakers have already sent them.
- [ ] Call lead/host + Executive assistant: Double check dates and time: Copy/paste from OLS public calendar. DO NOT CALCULATE MANUALLY 

# One week before **each** call
Note: Call leads/hosts should answer questions from speakers or facilitators when they have specific questions about the subjects of the call, or about the presentation (topics to be covered, to not cover, emphasis, etc). 

15. ## Setting up reminders
- [ ] Executive assistant: Send call lead/host a reminder of the call. Check if the etherpad, speakers and facilitators are ready. (Executive Assistant)
- [ ] Executive assistant: Send speakers a reminder of the call with the login info using [email templates](https://docs.google.com/document/d/1Go_na0zqY6_17FBNlX8xCD5hUd5FaaByth1EHoRH0T4/edit).
(Executive Assistant)

# 48 hours before the cohort call

16. ## Conducting final confirmations 
- [ ] Call lead/host: Double check with speakers and facilitators will be present at the call.
- [ ] Call lead/host: Check if the calendar invite coincides with the timing shown on the website, on otter.ai, and on the weekly mailing sent that week.
- [ ] Call lead/host: Check if otter.ai is set up right for the call: and that the connection to Zoom is enabled. 
- [ ] Call lead/host: Post on Slack inviting people to the call. 

# During the cohort

17. ## General during-cohort tasks 
- [ ] Coordinator: check if surveys have the right info on them - read them carefully before sending them. 
- [ ] Coordinator: send weekly CiviCRM mailings
- [ ] Coordinator: set up the mentor mid-term check
- [ ] Coordinator: send community members the [speaker nomination form](https://forms.gle/RW8KUf4pd3T9LaNB9)
- [ ] Coordinator: inform mentors a feedback about their mentees is expected towards the end of the cohort. This feedback is needed to better assess if the mentees are ready to graduate or not. 
- [ ] Coordinator: create an assessment form for mentors to assess their mentees in detail. Completing this form should be mandatory.
- [ ] Coordinator: create an assessment form for mentees to assess their mentors (this would be a new form for OLS-9).
- [ ] Coordinator: communicate via Slack and in some mailings, that to graduate, some minimum requirements need to be completed, and send them the graduation guide. 
- [ ] Coordinator: communicate/remind people at least 3 times via CiviCRM mailings and Slack, that people can nominate speakers for future cohorts.
- [ ] Coordinator: communicate via Slack and mailing how people can engage with the community, during or after their cohort participation 

18. ## Tasks after **each** call
- [ ]  Executive assistant: Email speakers using [email templates](https://docs.google.com/document/d/1Go_na0zqY6_17FBNlX8xCD5hUd5FaaByth1EHoRH0T4/edit) inviting them to join slack (if they are not there yet) and asking them to complete the honorarium form. 
- [ ] Facilitators: make sure the etherpad is completed (as much as possible), if there is something important missing, inform the Call lead/host so the Call lead can get that info (e.g. a speakers presentation).
 
19. ## Tasks ahead of graduations 
- [ ] Coordinator: send all cohort participants the graduation guide, reminding them there are some basic requirements. 
- [ ] Coordinator: send all cohort participants a reminder to attend the graduation rehearsals (make it mandatory?) 
- [ ] Coordinator: Check which mentors have given favourable feedback about their mentees’ readiness to graduate - and which haven’t. 
- [ ] Coordinator: remind mentors to fill out the mentee's assessment form and send it by a certain date. 
- [ ] Coordinator: set up restream 
- [ ] Coordinator: decide whether translation is needed 
- [ ] Coordinator: set up [zoom registration](https://www.youtube.com/watch?v=F927modarHY) (no Eventbrite anymore)
- [ ] Coordinator: sent out invites to all cohort members

# After graduation 
- [ ] Prepare the certificates of completion - [See tutorial](https://github.com/open-life-science/branding/tree/master/certificates) and this: https://github.com/open-life-science/branding/edit/master/certificates/README.md Please note these certificates need to be signed by Bérénice as director. Once downloaded from Inkscape, you need to ask Bérénice to sign them. 
- [ ] Send the certificates of completion to each cohort member
- [ ] Send cohort members the speaker nomination form 

# Slack management (To be completed - TBC)
- [ ] Explain to people where they should expect to find the Zoom links (explain they are not in the public calendar because the public calendar is public)... maybe add a Zoom link to all the calls in the weekly mailing? 

# CiviCRM management (TBC)

# Useful templates (TBC)

# Engaging cohort participants (TBC)
