### ISSUE TITLE
[OLS-9 Cohort call week 02] Checklist for the Call Leads

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/ols-9#25]
**Note: Call leads (also referred to as "hosts"), facilitators, coordinators, and assistants, please refer to the [OLS-9 Planning Long Check-list](https://github.com/open-life-science/ols-9/issues/1) for further details about _when_ to complete each of these tasks and for the related documentation.**

1. Call preparation
   * [x] Identify and email speakers (cc Coordinator and Assistant) 
   * [x] Send reminders to speakers before the call  (cc Coordinator and Assistant) 
   * [x] Prepare the Framapad notes
   * [x] Confirm facilitators for the week (2, one for the video processing and the other for the cohort call) (involve the Coordinator in this conversation)
   * [x] Share note link with the cohort call facilitator
   * [x] Review the week's plan including assignments, update as needed and share any questions/feedback with the team
3. Weekly CiviCRM mailings
   * [x] Send email to all cohort participants, make sure to include links to etherpad (see [OLS-9 Planning Long Check-list](https://github.com/open-life-science/ols-9/issues/1) for more details about what else to include in these mailings.
   * [x] Double check speakers have been invited, confirmed and reminded. 
5. Cohort Planning Sheet
   * [ ]  Add the link to the recording
   * [x]  Add names of Call lead and facilitators
   * [x]  Add speaker names in "Confirmed speaker"
8. Website
	* [x] Add person detail to `people.yaml` if needed
