### ISSUE TITLE
[OLS-9 Cohort call week 03] Checklist for the Call Leads

### ISSUE THREAD

**Issue by seunolufemi123** [open-life-science/ols-9#30]
Note: Call leads (also referred to as "hosts"), facilitators, coordinators, and assistants, please refer to the https://github.com/open-life-science/ols-9/issues/1 for further details about when to complete each of these tasks and for the related documentation.

1. Call preparation
- [ ]  Identify and email speakers (cc Coordinator and Assistant)
- [ ]  Send reminders to speakers before the call (cc Coordinator and Assistant)
- [ ]  Prepare the Framapad notes
- [ ]  Confirm facilitators for the week (2, one for the video processing and the other for the cohort call) (involve the Coordinator in this conversation)
- [ ]  Share note link with the cohort call facilitator
- [ ]  Review the week's plan including assignments, update as needed and share any questions/feedback with the team
2. Weekly CiviCRM mailings
- [ ]  Send email to all cohort participants, make sure to include links to etherpad (see https://github.com/open-life-science/ols-9/issues/1 for more details about what else to include in these mailings.
- [ ]  Double check speakers have been invited, confirmed and reminded.
3. Cohort Planning Sheet
- [ ]  Add the link to the recording
- [ ]  Add names of Call lead and facilitators
- [ ]  Add speaker names in "Confirmed speaker"
4. Website
- [ ]  Add person detail to people.yaml if needed
